# Generated by Django 4.0.1 on 2022-01-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Dzień szkolenia')),
                ('start_time', models.TimeField(verbose_name='Godzina rozpoczęcia')),
                ('duration', models.PositiveSmallIntegerField(default=1, verbose_name='Czas trwania(godz)')),
                ('cancellation', models.BooleanField(blank=True, default=False, verbose_name='Anulowanie?')),
                ('was_training', models.BooleanField(blank=True, default=False, null=True, verbose_name='Szkolenie odbyte?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(to='people.Student', verbose_name='Kursanci')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.trainer', verbose_name='Instruktor')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Czas trwania')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student', verbose_name='Instruktor')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('number_of_hours', models.PositiveSmallIntegerField(verbose_name='Liczba godzin')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Cena')),
                ('active', models.BooleanField(default=False, verbose_name='Aktywny')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
            ],
            options={
                'ordering': ['number_of_hours'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True, verbose_name='Dzień szkolenia')),
                ('start_time', models.TimeField(verbose_name='Godzina rozpoczęcia')),
                ('duration', models.PositiveSmallIntegerField(default=0, verbose_name='Czas trwania(godz)')),
                ('acceptance', models.BooleanField(default=False, verbose_name='Akceptacja')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dodatkowe informacje')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trainings.booking', verbose_name='Rezerwacja')),
                ('students', models.ManyToManyField(through='trainings.StudentTraining', to='people.Student', verbose_name='Kursanci')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.trainer', verbose_name='Instruktor')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='studenttraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training', verbose_name='Trening'),
        ),
    ]
