# Generated by Django 4.0.3 on 2022-04-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['day', 'start_time'], 'verbose_name_plural': 'Rezerwacje'},
        ),
        migrations.AlterModelOptions(
            name='trainingpacket',
            options={'ordering': ['is_active', 'number_of_hours'], 'verbose_name_plural': 'Pakiety treningowe'},
        ),
        migrations.RenameField(
            model_name='trainingpacket',
            old_name='active',
            new_name='is_active',
        ),
    ]
