# Generated by Django 4.0.3 on 2022-04-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_alter_booking_options_alter_trainingpacket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttraining',
            options={'verbose_name_plural': 'Przeprowadzone szkolenia'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['day', 'start_time'], 'verbose_name_plural': 'Szkolenia'},
        ),
    ]
