# Generated by Django 4.0.4 on 2022-04-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_trainer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Numer telefonu'),
        ),
    ]
